
#line 3 "<stdout>"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 147
#define YY_END_OF_BUFFER 148
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[609] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,  148,  147,  146,    1,
        3,  116,  138,  145,  146,  146,  146,  136,    4,  113,
      146,  112,  137,  137,  146,  146,    6,  137,  137,  137,
      137,  137,  137,  137,  137,  137,  137,  137,  137,  137,
      137,  137,  137,  137,  137,  146,  146,    5,   10,   10,
      137,  144,  140,  139,  144,  132,  123,  123,  130,  129,
      111,  145,  114,   85,  136,   36,   37,   29,    0,   32,
       33,   30,   35,   34,   31,   87,   88,  136,  136,    0,
      136,    0,    0,    0,    0,   84,  110,  108,  109,  137,

      137,   20,    2,  137,  137,  137,   94,  137,  137,   95,
      137,  137,  137,  137,  137,  137,   68,  137,  137,  137,
      120,  137,  137,  137,  137,  137,  137,  137,  137,   59,
      125,  137,  137,  137,  137,  137,  137,  137,  137,  137,
      137,   26,  137,  137,  137,  137,  137,  137,  137,  137,
      137,  137,  137,  137,  137,   93,  137,   66,  137,  137,
      137,    0,    7,    0,  115,   10,   10,   10,   10,   10,
       10,   10,   10,   10,   10,   10,   10,   10,   10,   10,
      137,  141,  143,  142,  132,  123,  129,    0,    0,    0,
        0,    0,   89,    0,   40,    0,   42,    0,    0,   41,

        0,    0,   43,    0,    0,    0,  136,    0,  136,  135,
       86,  137,  137,   25,   14,  137,  137,  137,  137,  137,
       12,   70,  137,  137,  137,  137,  137,  101,  137,  137,
      137,   75,  137,  137,  137,  137,  137,   99,  137,  137,
      118,  137,  137,  137,  107,  137,  137,  137,  137,  137,
       98,  137,  105,  106,  137,  137,  137,  137,   61,  137,
      137,  137,  137,  137,  128,  100,  137,  137,  137,  137,
      137,  137,  137,   27,  137,  137,  137,  137,  137,   28,
      137,   60,  137,    0,   10,   10,    9,    8,   10,   10,
       10,   10,   10,   10,   10,   10,   10,   10,   10,   10,

       10,   10,   10,   10,   10,   10,   10,  137,   36,    0,
        0,   39,    0,    0,    0,   91,    0,    0,    0,   34,
        0,   90,  117,  137,  137,  137,  137,  137,  137,  137,
       77,  137,  137,  121,   76,  137,   62,  137,   67,  137,
      137,  127,    0,    0,   73,  137,   92,  137,  137,  137,
       97,   64,   18,  137,  137,   19,  137,  137,  137,  137,
      104,  137,  137,  137,   23,   63,  137,  137,  137,  137,
      137,  103,  137,  126,  137,  137,    0,    0,  137,  137,
      137,  137,  137,   96,   10,   10,    9,    8,   10,   10,
       10,   10,   10,   10,   10,   10,   10,   10,   10,   10,

       10,   10,  137,    0,    0,   29,    0,   32,    0,    0,
        0,    0,    0,   31,    0,   81,   16,  102,   82,  137,
      137,  137,  137,  137,  137,  137,  137,  137,    0,    0,
      137,    0,  134,  137,  137,   71,    0,    0,   79,  137,
      137,  137,   11,  137,   21,   65,   80,   74,  137,  137,
      137,  137,  137,  137,  122,    0,  137,  124,  137,    0,
        0,   60,   10,   10,   10,   10,   10,   10,   10,   10,
       10,   10,   10,   10,  137,    0,    0,    0,   33,    0,
       30,   35,   38,   90,  137,  137,   83,   13,  137,   76,
      137,  137,   75,    0,  137,   54,  137,  137,    0,    0,

        0,   72,    0,    0,   61,    0,    0,    0,    0,   17,
       78,  137,    0,    0,  137,   44,    0,  137,    0,    0,
        0,   10,   10,   10,   10,   10,   10,   10,   10,   10,
      137,   36,   37,   91,   24,    0,    0,    0,    0,  137,
      131,  137,   51,   15,  137,   48,    0,    0,    0,    0,
        0,   22,    0,  133,  137,    0,    0,   49,   10,   10,
       10,  119,    0,    0,  137,   62,  137,    0,    0,   45,
       50,   47,   53,  133,  137,    0,    0,   46,   52,   69,
       71,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,   58,    0,   57,    0,   56,   55,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    6,    1,    1,    7,    8,    1,
        1,    1,    9,    1,   10,   11,    1,   12,   12,   13,
       12,   12,   12,   12,   12,   12,   12,    1,   14,   15,
       16,   17,    1,    1,   18,   18,   18,   18,   19,   18,
       18,   20,   18,   18,   18,   18,   18,   18,   18,   21,
       18,   18,   22,   18,   18,   18,   18,   18,   18,   18,
       23,   24,   25,    1,   18,    1,   26,   27,   28,   29,

       30,   31,   32,   33,   34,   35,   36,   37,   38,   39,
       40,   41,   42,   43,   44,   45,   46,   47,   48,   49,
       50,   51,   52,   53,   54,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[55] =
    {   0,
        1,    2,    3,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    4,    1,    1,    1,    1,    5,    5,    5,
        5,    5,    1,    1,    1,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    1,    1,    1
    } ;

static const flex_int16_t yy_base[622] =
    {   0,
        0,    0,    0,   47,   54,   57,   81,    0,    0,    0,
        0,    0,  135,    0,  189,    0,  896,  897,  897,  897,
      897,  879,  897,    0,  887,  876,  232,  272,  897,   51,
      876,  875,    0,  860,  864,  885,  897,   29,  216,  224,
       39,  260,   37,  218,  216,  270,  253,  847,  855,  842,
      288,  286,   30,  210,  244,  286,  831,  897,    0,  320,
      844,  897,  897,  897,  289,    0,  897,    0,  897,    0,
      897,    0,  897,  897,  324,  842,  851,  264,  223,  850,
      312,  295,  326,  839,  305,  897,  897,  360,    0,  368,
      897,  849,  848,  831,  842,  857,  897,  897,  897,    0,

      830,  897,  897,  832,  842,  297,  844,  293,  300,    0,
      821,  829,  827,  823,  825,  254,    0,  820,  832,  836,
      337,  817,  264,  831,  818,  230,  815,  817,  822,    0,
        0,  339,  811,  823,  814,  806,  314,  802,  811,  802,
      345,    0,  814,  322,  803,  814,  799,  806,  841,   25,
      346,  350,  799,  815,  346,  799,  362,  798,  788,  793,
      366,  394,  833,  832,  897,    0,  386,  382,  794,  803,
      376,  373,  802,  379,  380,  383,  791,  378,    0,    0,
      801,  897,  897,  897,    0,    0,    0,  784,  789,  783,
      797,  791,  897,  793,  897,  780,  897,  793,  789,  897,

      774,  793,  897,  777,  773,  787,  413,  409,  417,  897,
      897,  785,  767,    0,    0,  773,  773,  771,  762,  764,
        0,    0,  763,  766,  778,  777,  754,    0,  770,  768,
      763,  755,  760,  753,  763,  766,  415,    0,  758,  750,
        0,  755,  760,  754,    0,  756,  744,  743,  757,  742,
        0,  755,    0,    0,  754,  754,  737,  742,  746,  750,
      748,  744,  732,  745,  772,    0,  743,  738,  726,  736,
      403,  724,  725,  728,  394,  422,  736,  731,  734,    0,
      718,  717,  728,  757,  432,    0,    0,    0,  714,  719,
      713,  727,  721,    0,  723,    0,  710,    0,  723,  719,

        0,  704,  723,    0,  707,  703,  717,  714,  699,  698,
      697,  897,  709,  695,  694,  704,  704,  691,  692,  897,
      689,  688,    0,  702,  683,  717,  681,  698,  687,  696,
        0,  688,  688,    0,  693,  683,  691,  690,    0,  433,
      678,    0,  434,  715,    0,  672,    0,  683,  669,  670,
        0,  436,    0,  668,  669,    0,  679,  677,  664,  662,
        0,  662,  661,  660,    0,    0,  675,  670,  663,  675,
      661,    0,  654,    0,  652,  695,  446,  693,  664,  657,
      650,  447,  659,    0,  440,  442,    0,    0,  646,  645,
      644,    0,  656,  642,  641,  651,  651,  638,  639,    0,

      636,  635,  639,  638,  647,  897,  643,  897,  642,  628,
      628,  639,  626,  897,  637,    0,    0,    0,    0,  639,
      630,  624,  636,  617,  635,  633,  617,  632,  448,  657,
      615,  627,    0,  612,  627,  621,  454,  651,    0,  457,
      623,  459,    0,  608,    0,  460,    0,    0,  461,  621,
      621,  604,  463,  616,  645,  615,  462,    0,  465,  466,
      642,    0,  604,  613,    0,  609,    0,  608,  594,  594,
      605,  592,    0,  603,  592,  596,  590,  587,  897,  587,
      897,  897,  897,  897,  591,  467,  471,    0,  595,    0,
      626,  597,    0,  595,  595,  897,  594,  596,  591,  455,

      618,    0,  473,  617,    0,  475,  616,  477,  615,    0,
        0,  586,  478,  613,  582,  897,  612,  574,  466,  609,
      580,  572,  566,  563,    0,  563,    0,    0,    0,    0,
      600,  897,  897,  897,    0,  480,  599,  498,  595,  549,
      575,  527,  897,    0,  519,  897,  525,  520,  522,  520,
      519,    0,  517,    0,  517,  515,  510,  897,    0,    0,
        0,  897,  512,  511,  510,    0,  509,  506,  503,  897,
      897,  897,  897,    0,  529,  497,  494,  897,  897,    0,
        0,  480,  491,  478,  488,  503,  471,  505,  448,  506,
      463,  508,  509,  407,  510,  324,  512,  341,  293,  517,

      304,  897,  219,  897,   44,  897,  897,  897,  557,  562,
      567,  569,  574,  576,  578,  580,  585,  590,  595,  599,
      601
    } ;

static const flex_int16_t yy_def[622] =
    {   0,
      609,  609,  608,    3,  610,  610,  608,    7,  609,  609,
      609,  609,  608,   13,  608,   15,  608,  608,  608,  608,
      608,  608,  608,  611,  608,  608,  608,  608,  608,  608,
      608,  608,  612,  612,  608,  608,  608,  612,  612,  612,
      612,  612,  612,  612,  612,  612,  612,  612,  612,  612,
      612,  612,  612,  612,  612,  608,  608,  608,  613,  613,
      612,  608,  608,  608,  608,  614,  608,  615,  608,  616,
      608,  611,  608,  608,  608,  608,  608,  608,  608,  608,
      608,  608,  608,  608,  608,  608,  608,  608,   28,  608,
      608,  608,  608,  608,  608,  608,  608,  608,  608,  612,

      612,  608,  608,  612,  612,  612,  612,  612,  612,  612,
      612,  612,  612,  612,  612,  612,  612,  612,  612,  612,
      612,  612,  612,  612,  612,  612,  612,  612,  612,  612,
      612,  612,  612,  612,  612,  612,  612,  612,  612,  612,
      612,  612,  612,  612,  612,  612,  612,  612,  612,  612,
      612,  612,  612,  612,  612,  612,  612,  612,  612,  612,
      612,  608,  608,  617,  608,  613,  613,  613,  613,  613,
      613,  613,  613,  613,  613,  613,  613,  613,  613,  613,
      612,  608,  608,  608,  614,  615,  616,  608,  608,  608,
      608,  608,  608,  608,  608,  608,  608,  608,  608,  608,

      608,  608,  608,  608,  608,  608,  608,  608,  608,  608,
      608,  612,  612,  612,  612,  612,  612,  612,  612,  612,
      612,  612,  612,  612,  612,  612,  612,  612,  612,  612,
      612,  612,  612,  612,  612,  612,  612,  612,  612,  612,
      612,  612,  612,  612,  612,  612,  612,  612,  612,  612,
      612,  612,  612,  612,  612,  612,  612,  612,  612,  612,
      612,  612,  612,  612,  608,  612,  612,  612,  612,  612,
      612,  612,  612,  612,  612,  612,  612,  612,  612,  612,
      612,  612,  612,  617,  613,  613,  618,  619,  613,  613,
      613,  613,  613,  613,  613,  613,  613,  613,  613,  613,

      613,  613,  613,  613,  613,  613,  613,  612,  608,  608,
      608,  608,  608,  608,  608,  608,  608,  608,  608,  608,
      608,  608,  612,  612,  612,  612,  612,  612,  612,  612,
      612,  612,  612,  612,  612,  612,  612,  612,  612,  612,
      612,  612,  608,  608,  612,  612,  612,  612,  612,  612,
      612,  612,  612,  612,  612,  612,  612,  612,  612,  612,
      612,  612,  612,  612,  612,  612,  612,  612,  612,  612,
      612,  612,  612,  612,  612,  612,  608,  608,  612,  612,
      612,  612,  612,  612,  613,  613,  618,  619,  613,  613,
      613,  613,  613,  613,  613,  613,  613,  613,  613,  613,

      613,  613,  612,  608,  608,  608,  608,  608,  608,  608,
      608,  608,  608,  608,  608,  612,  612,  612,  612,  612,
      612,  612,  612,  612,  612,  612,  612,  612,  608,  608,
      612,  608,  612,  612,  612,  612,  608,  608,  612,  612,
      612,  612,  612,  612,  612,  612,  612,  612,  612,  612,
      612,  612,  612,  612,  608,  608,  612,  612,  612,  608,
      608,  612,  613,  613,  613,  613,  613,  613,  613,  613,
      613,  613,  613,  613,  612,  608,  608,  608,  608,  608,
      608,  608,  608,  608,  612,  612,  612,  612,  612,  612,
      612,  612,  612,  608,  612,  608,  612,  612,  608,  608,

      608,  612,  608,  608,  612,  608,  608,  608,  608,  612,
      612,  612,  608,  608,  612,  608,  620,  612,  608,  608,
      608,  613,  613,  613,  613,  613,  613,  613,  613,  613,
      612,  608,  608,  608,  612,  608,  608,  608,  608,  612,
      608,  612,  608,  612,  612,  608,  608,  608,  608,  608,
      608,  612,  608,  621,  612,  608,  608,  608,  613,  613,
      613,  608,  608,  608,  612,  612,  612,  608,  608,  608,
      608,  608,  608,  621,  612,  608,  608,  608,  608,  612,
      612,  608,  608,  608,  608,  608,  608,  608,  608,  608,
      608,  608,  608,  608,  608,  608,  608,  608,  608,  608,

      608,  608,  608,  608,  608,  608,  608,    0,  608,  608,
      608,  608,  608,  608,  608,  608,  608,  608,  608,  608,
      608
    } ;

static const flex_int16_t yy_nxt[952] =
    {   0,
       19,   20,   21,   22,   23,   24,   25,   19,   19,   26,
       27,   28,   28,   29,   30,   31,   32,   33,   33,   34,
       33,   33,   35,   36,   37,   38,   39,   40,   41,   42,
       43,   33,   44,   45,   33,   33,   46,   47,   48,   49,
       50,   33,   51,   52,   53,   54,   33,   55,   33,   33,
       33,   56,   57,   58,   59,  104,   63,   60,   64,   63,
       96,   64,  155,  266,  118,   61,   97,  105,  119,  156,
      126,  106,  120,  107,  607,  267,  127,   65,  121,  128,
       65,   18,   18,   18,   18,   18,   18,   18,   18,   18,
       18,   18,   18,   18,   18,   18,   18,   18,   66,   66,

       66,   66,   66,   18,   18,   18,   66,   66,   66,   66,
       66,   66,   66,   66,   66,   66,   66,   66,   66,   66,
       66,   66,   66,   66,   66,   66,   66,   66,   66,   66,
       66,   66,   18,   18,   18,   67,   67,   18,   67,   67,
       67,   67,   67,   67,   67,   67,   67,   67,   67,   67,
       67,   67,   68,   68,   68,   68,   68,   67,   67,   67,
       68,   68,   68,   68,   68,   68,   68,   68,   68,   68,
       68,   68,   68,   68,   68,   68,   68,   68,   68,   68,
       68,   68,   68,   68,   68,   68,   67,   67,   67,   69,
       69,   69,   69,   69,   69,   69,   69,   69,   69,   69,

       69,   69,   69,   69,   69,   69,   70,   70,   70,   70,
       70,   69,   69,   69,   70,   70,   70,   70,   70,   70,
       70,   70,   70,   70,   70,   70,   70,   70,   70,   70,
       70,   70,   70,   70,   70,   70,   70,   70,   70,   70,
       69,   69,   69,   75,   75,  108,  131,  129,  157,  606,
      158,  111,  192,  112,  132,  109,  113,  114,   76,   77,
      115,   78,  130,  116,   79,  110,  239,  193,   80,  159,
       81,  117,  240,  160,   82,   83,   84,  161,  138,   85,
       86,   87,   88,   89,   89,  122,  139,  162,  163,  190,
       90,  164,  140,  182,  227,  133,  123,  228,  124,  134,

      235,   90,  191,  135,  136,   91,  600,  236,  125,  137,
       92,  148,  183,  144,   93,   94,   95,  145,  149,  150,
      198,  146,  147,  604,  215,  151,  152,  153,  199,  218,
      154,  167,  167,  184,  205,   75,   75,  219,  206,  216,
      168,  195,   90,  597,  220,  251,  169,  170,  221,  171,
      259,  196,  172,   90,  602,  200,  173,   91,  174,  197,
      260,  252,  175,  176,  177,  201,  244,  178,  179,  180,
      202,  207,  207,  203,  256,  274,  208,  208,   90,  209,
      209,  232,  268,  245,  233,  246,  270,  257,  275,   90,
      277,  269,  271,   91,  282,  162,  163,  167,  167,  164,

      287,  291,  293,  288,  285,  299,  278,  306,  296,  593,
      283,  307,  301,  300,  292,  285,  343,  294,  297,  286,
      209,  209,  302,  377,  207,  207,  298,  303,  209,  209,
      304,   90,  370,  375,  429,  343,  371,  437,  344,  376,
      385,  385,   90,  386,  386,  378,   91,  377,  460,  429,
       91,  386,  386,  386,  386,  437,  430,  344,  500,  438,
      503,  506,  508,  517,  513,  590,  519,  460,  536,  378,
      461,  430,  538,  432,  503,  286,  506,  438,  508,  513,
      501,  536,  504,  507,  509,  456,  514,  494,  520,  461,
      537,  547,  595,  499,  539,  518,  504,  548,  507,  538,

      509,  514,  556,  537,  590,  521,  593,  590,  557,  597,
      593,  600,  549,  597,  550,  592,  551,  553,  600,  563,
      589,  539,  588,  587,  586,  585,  591,  584,  594,  591,
      517,  598,  594,  601,  583,  598,  582,  564,  581,  580,
      601,  579,  578,  577,  576,  596,  575,  573,  599,  572,
      571,  603,  570,  569,  568,  567,  605,   18,   18,   18,
       18,   18,   62,   62,   62,   62,   62,   72,   72,  566,
       72,   72,  100,  100,  166,  166,  541,  166,  166,  185,
      185,  186,  186,  187,  187,  284,  284,  284,  284,  284,
      387,  387,  565,  387,  387,  388,  388,  538,  388,  388,

      554,  536,  562,  554,  574,  574,  561,  294,  560,  559,
      558,  519,  555,  517,  376,  513,  552,  508,  506,  503,
      500,  546,  545,  334,  544,  543,  542,  541,  540,  535,
      534,  193,  533,  532,  531,  530,  529,  528,  527,  526,
      525,  524,  523,  522,  460,  516,  455,  515,  512,  511,
      510,  505,  502,  437,  498,  497,  130,  496,  495,  429,
      493,  492,  491,  490,  489,  488,  487,  486,  485,  484,
      483,  482,  481,  480,  479,  478,  477,  476,  475,  474,
      473,  472,  471,  470,  469,  468,  467,  466,  465,  464,
      463,  462,  459,  458,  457,  377,  455,  454,  453,  452,

      451,  450,  449,  448,  447,  446,  445,  444,  443,  442,
      441,  440,  439,  436,  435,  434,  433,  343,  431,  428,
      427,  426,  425,  424,  423,  422,  421,  420,  419,  418,
      417,  416,  415,  414,  413,  412,  411,  410,  409,  408,
      407,  406,  405,  404,  403,  402,  401,  400,  399,  398,
      397,  396,  395,  394,  393,  392,  391,  390,  389,  163,
      384,  383,  382,  381,  380,  379,  374,  373,  372,  369,
      368,  367,  366,  265,  365,  364,  363,  362,  361,  360,
      359,  358,  357,  356,  355,  354,  353,  352,  351,  350,
      349,  348,  347,  346,  345,  342,  341,  340,  339,  338,

      337,  336,  335,  334,  333,  332,  331,  330,  329,  328,
      327,  326,  325,  324,  323,  322,  321,  320,  319,  318,
      317,  316,  315,  314,  313,  312,  311,  310,  309,  308,
      305,  295,  290,  289,  163,  163,  281,  280,  279,  276,
      273,  272,  265,  264,  263,  262,  261,  258,  255,  254,
      253,  250,  249,  248,  247,  243,  242,  241,  238,  237,
      234,  231,  230,  229,  226,  225,  224,  223,  222,  217,
      214,  213,  212,  211,  210,  210,  210,  210,  204,  194,
      189,  188,  181,  165,  143,  142,  141,  103,  102,  101,
       99,   98,   74,   73,   71,  608,   17,  608,  608,  608,

      608,  608,  608,  608,  608,  608,  608,  608,  608,  608,
      608,  608,  608,  608,  608,  608,  608,  608,  608,  608,
      608,  608,  608,  608,  608,  608,  608,  608,  608,  608,
      608,  608,  608,  608,  608,  608,  608,  608,  608,  608,
      608,  608,  608,  608,  608,  608,  608,  608,  608,  608,
      608
    } ;

static const flex_int16_t yy_chk[952] =
    {   0,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    4,   38,    5,    4,    5,    6,
       30,    6,   53,  150,   41,    4,   30,   38,   41,   53,
       43,   38,   41,   38,  605,  150,   43,    5,   41,   43,
        6,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,

        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   15,
       15,   15,   15,   15,   15,   15,   15,   15,   15,   15,

       15,   15,   15,   15,   15,   15,   15,   15,   15,   15,
       15,   15,   15,   15,   15,   15,   15,   15,   15,   15,
       15,   15,   15,   15,   15,   15,   15,   15,   15,   15,
       15,   15,   15,   15,   15,   15,   15,   15,   15,   15,
       15,   15,   15,   27,   27,   39,   45,   44,   54,  603,
       54,   40,   79,   40,   45,   39,   40,   40,   27,   27,
       40,   27,   44,   40,   27,   39,  126,   79,   27,   55,
       27,   40,  126,   55,   27,   27,   27,   55,   47,   27,
       27,   27,   28,   28,   28,   42,   47,   56,   56,   78,
       28,   56,   47,   65,  116,   46,   42,  116,   42,   46,

      123,   28,   78,   46,   46,   28,  601,  123,   42,   46,
       28,   52,   65,   51,   28,   28,   28,   51,   52,   52,
       82,   51,   51,  599,  106,   52,   52,   52,   82,  108,
       52,   60,   60,   65,   85,   75,   75,  108,   85,  106,
       60,   81,   75,  598,  109,  137,   60,   60,  109,   60,
      144,   81,   60,   75,  596,   83,   60,   75,   60,   81,
      144,  137,   60,   60,   60,   83,  132,   60,   60,   60,
       83,   88,   88,   83,  141,  155,   90,   90,   88,   90,
       90,  121,  151,  132,  121,  132,  152,  141,  155,   88,
      157,  151,  152,   88,  161,  162,  162,  167,  167,  162,

      168,  171,  172,  168,  167,  175,  157,  178,  174,  594,
      161,  178,  176,  175,  171,  167,  237,  172,  174,  167,
      208,  208,  176,  276,  207,  207,  174,  176,  209,  209,
      176,  207,  271,  275,  340,  343,  271,  352,  237,  275,
      285,  285,  207,  285,  285,  276,  207,  377,  382,  429,
      209,  385,  385,  386,  386,  437,  340,  343,  440,  352,
      442,  446,  449,  457,  453,  591,  459,  460,  486,  377,
      382,  429,  487,  343,  503,  386,  506,  437,  508,  513,
      440,  536,  442,  446,  449,  377,  453,  429,  459,  460,
      486,  500,  589,  437,  487,  457,  503,  500,  506,  538,

      508,  513,  519,  536,  586,  460,  588,  590,  519,  592,
      593,  595,  503,  597,  506,  587,  508,  513,  600,  536,
      585,  538,  584,  583,  582,  577,  586,  576,  588,  590,
      575,  592,  593,  595,  569,  597,  568,  538,  567,  565,
      600,  564,  563,  557,  556,  590,  555,  553,  593,  551,
      550,  597,  549,  548,  547,  545,  600,  609,  609,  609,
      609,  609,  610,  610,  610,  610,  610,  611,  611,  542,
      611,  611,  612,  612,  613,  613,  541,  613,  613,  614,
      614,  615,  615,  616,  616,  617,  617,  617,  617,  617,
      618,  618,  540,  618,  618,  619,  619,  539,  619,  619,

      620,  537,  531,  620,  621,  621,  526,  524,  523,  522,
      521,  520,  518,  517,  515,  514,  512,  509,  507,  504,
      501,  499,  498,  497,  495,  494,  492,  491,  489,  485,
      480,  478,  477,  476,  475,  474,  472,  471,  470,  469,
      468,  466,  464,  463,  461,  456,  455,  454,  452,  451,
      450,  444,  441,  438,  436,  435,  434,  432,  431,  430,
      428,  427,  426,  425,  424,  423,  422,  421,  420,  415,
      413,  412,  411,  410,  409,  407,  405,  404,  403,  402,
      401,  399,  398,  397,  396,  395,  394,  393,  391,  390,
      389,  383,  381,  380,  379,  378,  376,  375,  373,  371,

      370,  369,  368,  367,  364,  363,  362,  360,  359,  358,
      357,  355,  354,  350,  349,  348,  346,  344,  341,  338,
      337,  336,  335,  333,  332,  330,  329,  328,  327,  326,
      325,  324,  322,  321,  319,  318,  317,  316,  315,  314,
      313,  311,  310,  309,  308,  307,  306,  305,  303,  302,
      300,  299,  297,  295,  293,  292,  291,  290,  289,  284,
      283,  282,  281,  279,  278,  277,  274,  273,  272,  270,
      269,  268,  267,  265,  264,  263,  262,  261,  260,  259,
      258,  257,  256,  255,  252,  250,  249,  248,  247,  246,
      244,  243,  242,  240,  239,  236,  235,  234,  233,  232,

      231,  230,  229,  227,  226,  225,  224,  223,  220,  219,
      218,  217,  216,  213,  212,  206,  205,  204,  202,  201,
      199,  198,  196,  194,  192,  191,  190,  189,  188,  181,
      177,  173,  170,  169,  164,  163,  160,  159,  158,  156,
      154,  153,  149,  148,  147,  146,  145,  143,  140,  139,
      138,  136,  135,  134,  133,  129,  128,  127,  125,  124,
      122,  120,  119,  118,  115,  114,  113,  112,  111,  107,
      105,  104,  101,   96,   95,   94,   93,   92,   84,   80,
       77,   76,   61,   57,   50,   49,   48,   36,   35,   34,
       32,   31,   26,   25,   22,   17,  608,  608,  608,  608,

      608,  608,  608,  608,  608,  608,  608,  608,  608,  608,
      608,  608,  608,  608,  608,  608,  608,  608,  608,  608,
      608,  608,  608,  608,  608,  608,  608,  608,  608,  608,
      608,  608,  608,  608,  608,  608,  608,  608,  608,  608,
      608,  608,  608,  608,  608,  608,  608,  608,  608,  608,
      608
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "picl.l"
#line 2 "picl.l"
/*
 * Changes by Gunnar Ritter, Freiburg i. Br., Germany, October 2005.
 *
 * Derived from Plan 9 v4 /sys/src/cmd/pic/
 *
 * Copyright (C) 2003, Lucent Technologies Inc. and others.
 * All Rights Reserved.
 *
 * Distributed under the terms of the Lucent Public License Version 1.02.
 */

/*	Sccsid @(#)picl.l	1.9 (gritter) 8/6/06	*/
#line 869 "<stdout>"

#line 24 "picl.l"
#ifndef	FLEX_SCANNER
#undef	input
#undef	unput
#endif	/* !FLEX_SCANNER */
/* #include <stdio.h> lex puts one out for us */
#include <ctype.h>
#include <stdlib.h>
#include <unistd.h>
#include "pic.h"
#include "y.tab.h"

#ifdef	FLEX_SCANNER
#undef	YY_INPUT
#define	YY_INPUT(buf, result, max_size) { \
	int	c = xxinput(); \
	result = (c == EOF || c == 0) ? YY_NULL : (buf[0] = c, 1); \
}
#define	witchcraft	YY_START
#else	/* !FLEX_SCANNER */
#define	witchcraft	yybgin-yysvec-1
#endif	/* !FLEX_SCANNER */

extern	char	*filename;
extern	struct	symtab	symtab[];

void	pbstr(char *);
void	dodef(struct symtab *stp);
void	undefine(char *s);
void	shell_init(void), shell_exec(void), shell_text(char *);
void	endfor(void);

int	yyback(int *, int);
int	yylook(void);
int	yywrap(void);

#define	CADD	cbuf[clen++]=yytext[0]; \
		if (clen>=CBUFLEN-1) { WARNING("string too long", cbuf); BEGIN A; }
#define	CBUFLEN	500
char	cbuf[CBUFLEN];
int	c, clen, cflag, delim;
int	ifsw	= 0;	/* 1 if if statement in progress */
#line 913 "<stdout>"
#line 914 "<stdout>"

#define INITIAL 0
#define A 1
#define str 2
#define def 3
#define xsc 4
#define br 5
#define thru 6
#define sh 7

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		YY_CURRENT_BUFFER_LVALUE->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 73 "picl.l"

#line 75 "picl.l"
	switch (witchcraft) {
	case 0:
		BEGIN A;
		break;
	case xsc:
		BEGIN A;
		return('}');
	case br:
		BEGIN A;
		return(']');
	}

#line 1156 "<stdout>"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 609 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 897 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 87 "picl.l"
;
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 88 "picl.l"
;
	YY_BREAK
case 3:
/* rule 3 can match eol */
YY_RULE_SETUP
#line 89 "picl.l"
{ return(ST); }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 90 "picl.l"
{ return(ST); }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 91 "picl.l"
{ BEGIN xsc; return(ST); }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 92 "picl.l"
{ BEGIN br; return(ST); }
	YY_BREAK
case 7:
/* rule 7 can match eol */
YY_RULE_SETUP
#line 93 "picl.l"
{ return(yylval.i = yytext[0]); }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 95 "picl.l"
{ if (curfile == infile) WARNING(".PS found inside .PS/.PE"); }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 96 "picl.l"
{ if (curfile == infile) {
			yylval.p = PEstring = tostring(yytext);
			return(EOF);
		  }
		}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 101 "picl.l"
{ yylval.p = tostring(yytext); return(TROFF); }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 103 "picl.l"
return(yylval.i = PRINT);
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 104 "picl.l"
return(yylval.i = BOX);
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 105 "picl.l"
return(yylval.i = CIRCLE);
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 106 "picl.l"
return(yylval.i = ARC);
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 107 "picl.l"
return(yylval.i = ELLIPSE);
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 108 "picl.l"
return(yylval.i = ARROW);
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 109 "picl.l"
return(yylval.i = SPLINE);
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 110 "picl.l"
return(yylval.i = LINE);
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 111 "picl.l"
return(yylval.i = MOVE);
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 112 "picl.l"
return(yylval.i = BLOCK);
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 113 "picl.l"
return(RESET);
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 114 "picl.l"
return(SPRINTF);
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 116 "picl.l"
return(SAME);
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 117 "picl.l"
return(BETWEEN);
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 118 "picl.l"
return(AND);
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 120 "picl.l"
;
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 121 "picl.l"
;
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 122 "picl.l"
;
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 124 "picl.l"
{ yylval.i = EAST; return(CORNER); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 125 "picl.l"
{ yylval.i = EAST; return(CORNER); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 126 "picl.l"
{ yylval.i = WEST; return(CORNER); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 127 "picl.l"
{ yylval.i = WEST; return(CORNER); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 128 "picl.l"
{ yylval.i = NORTH; return(CORNER); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 129 "picl.l"
{ yylval.i = NORTH; return(CORNER); }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 130 "picl.l"
{ yylval.i = SOUTH; return(CORNER); }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 131 "picl.l"
{ yylval.i = SOUTH; return(CORNER); }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 132 "picl.l"
{ yylval.i = CENTER; return(CORNER); }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 133 "picl.l"
{ yylval.i = START; return(CORNER); }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 134 "picl.l"
{ yylval.i = END; return(CORNER); }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 135 "picl.l"
{ yylval.i = NE; return(CORNER); }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 136 "picl.l"
{ yylval.i = SE; return(CORNER); }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 137 "picl.l"
{ yylval.i = NW; return(CORNER); }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 138 "picl.l"
{ yylval.i = SW; return(CORNER); }
	YY_BREAK
case 44:
/* rule 44 can match eol */
YY_RULE_SETUP
#line 140 "picl.l"
{ yylval.i = NORTH; return(CORNER); }
	YY_BREAK
case 45:
/* rule 45 can match eol */
YY_RULE_SETUP
#line 141 "picl.l"
{ yylval.i = NORTH; return(CORNER); }
	YY_BREAK
case 46:
/* rule 46 can match eol */
YY_RULE_SETUP
#line 142 "picl.l"
{ yylval.i = SOUTH; return(CORNER); }
	YY_BREAK
case 47:
/* rule 47 can match eol */
YY_RULE_SETUP
#line 143 "picl.l"
{ yylval.i = SOUTH; return(CORNER); }
	YY_BREAK
case 48:
/* rule 48 can match eol */
YY_RULE_SETUP
#line 144 "picl.l"
{ yylval.i = WEST; return(CORNER); }
	YY_BREAK
case 49:
/* rule 49 can match eol */
YY_RULE_SETUP
#line 145 "picl.l"
{ yylval.i = WEST; return(CORNER); }
	YY_BREAK
case 50:
/* rule 50 can match eol */
YY_RULE_SETUP
#line 146 "picl.l"
{ yylval.i = EAST; return(CORNER); }
	YY_BREAK
case 51:
/* rule 51 can match eol */
YY_RULE_SETUP
#line 147 "picl.l"
{ yylval.i = EAST; return(CORNER); }
	YY_BREAK
case 52:
/* rule 52 can match eol */
YY_RULE_SETUP
#line 148 "picl.l"
{ yylval.i = CENTER; return(CORNER); }
	YY_BREAK
case 53:
/* rule 53 can match eol */
YY_RULE_SETUP
#line 149 "picl.l"
{ yylval.i = START; return(CORNER); }
	YY_BREAK
case 54:
/* rule 54 can match eol */
YY_RULE_SETUP
#line 150 "picl.l"
{ yylval.i = END; return(CORNER); }
	YY_BREAK
case 55:
/* rule 55 can match eol */
YY_RULE_SETUP
#line 151 "picl.l"
{ yylval.i = NE; return(CORNER); }
	YY_BREAK
case 56:
/* rule 56 can match eol */
YY_RULE_SETUP
#line 152 "picl.l"
{ yylval.i = SE; return(CORNER); }
	YY_BREAK
case 57:
/* rule 57 can match eol */
YY_RULE_SETUP
#line 153 "picl.l"
{ yylval.i = NW; return(CORNER); }
	YY_BREAK
case 58:
/* rule 58 can match eol */
YY_RULE_SETUP
#line 154 "picl.l"
{ yylval.i = SW; return(CORNER); }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 156 "picl.l"
{ yylval.i = HEIGHT; return(ATTR); }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 157 "picl.l"
{ yylval.i = WIDTH; return(ATTR); }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 158 "picl.l"
{ yylval.i = RADIUS; return(ATTR); }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 159 "picl.l"
{ yylval.i = DIAMETER; return(ATTR); }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 160 "picl.l"
{ yylval.i = SIZE; return(ATTR); }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 161 "picl.l"
{ yylval.i = LEFT; return(DIR); }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 162 "picl.l"
{ yylval.i = RIGHT; return(DIR); }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 163 "picl.l"
{ yylval.i = UP; return(DIR); }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 164 "picl.l"
{ yylval.i = DOWN; return(DIR); }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 165 "picl.l"
{ yylval.i = CW; return(ATTR); }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 166 "picl.l"
{ yylval.i = CW; return(ATTR); }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 167 "picl.l"
{ yylval.i = CCW; return(ATTR); }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 168 "picl.l"
{ yylval.i = INVIS; return(ATTR); }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 169 "picl.l"
{ yylval.i = INVIS; return ATTR; }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 170 "picl.l"
return(yylval.i = FILL);
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 171 "picl.l"
;
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 172 "picl.l"
return(yylval.i = DOT);
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 173 "picl.l"
return(yylval.i = DASH);
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 174 "picl.l"
return(yylval.i = CHOP);
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 176 "picl.l"
{ yylval.i = SPREAD; return TEXTATTR; }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 177 "picl.l"
{ yylval.i = LJUST; return TEXTATTR; }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 178 "picl.l"
{ yylval.i = RJUST; return TEXTATTR; }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 179 "picl.l"
{ yylval.i = ABOVE; return TEXTATTR; }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 180 "picl.l"
{ yylval.i = BELOW; return TEXTATTR; }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 181 "picl.l"
{ yylval.i = CENTER; return TEXTATTR; }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 183 "picl.l"
{ yylval.i = HEAD1; return(HEAD); }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 184 "picl.l"
{ yylval.i = HEAD2; return(HEAD); }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 185 "picl.l"
{ yylval.i = HEAD12; return(HEAD); }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 187 "picl.l"
return(yylval.i = DOTX);
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 188 "picl.l"
return(yylval.i = DOTY);
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 189 "picl.l"
return(yylval.i = DOTHT);
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 190 "picl.l"
return(yylval.i = DOTWID);
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 191 "picl.l"
return(yylval.i = DOTRAD);
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 193 "picl.l"
return(yylval.i = FROM);
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 194 "picl.l"
return(yylval.i = TO);
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 195 "picl.l"
return(yylval.i = AT);
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 196 "picl.l"
return(yylval.i = BY);
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 197 "picl.l"
return(yylval.i = WITH);
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 198 "picl.l"
return(yylval.i = LAST);
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 200 "picl.l"
return(LOG);
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 201 "picl.l"
return(EXP);
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 202 "picl.l"
return(SIN);
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 203 "picl.l"
return(COS);
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 204 "picl.l"
return(ATAN2);
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 205 "picl.l"
return(SQRT);
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 206 "picl.l"
return(RAND);
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 207 "picl.l"
return(MAX);
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 208 "picl.l"
return(MIN);
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 209 "picl.l"
return(INT);
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 211 "picl.l"
return(EQ);
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 212 "picl.l"
return(GE);
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 213 "picl.l"
return(LE);
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 214 "picl.l"
return(NEQ);
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 215 "picl.l"
return(GT);
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 216 "picl.l"
return(LT);
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 217 "picl.l"
return(ANDAND);
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 218 "picl.l"
return(OROR);
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 219 "picl.l"
return(NOT);	
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 221 "picl.l"
return(yylval.i = HERE);
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 223 "picl.l"
return(FOR);
	YY_BREAK
case 119:
/* rule 119 can match eol */
YY_RULE_SETUP
#line 224 "picl.l"
{ endfor(); }
	YY_BREAK
case 120:
YY_RULE_SETUP
#line 225 "picl.l"
{ yylval.p = delimstr("loop body"); return(DOSTR); }
	YY_BREAK
case 121:
YY_RULE_SETUP
#line 227 "picl.l"
return(COPY);
	YY_BREAK
case 122:
YY_RULE_SETUP
#line 228 "picl.l"
{ BEGIN thru; return(THRU); }
	YY_BREAK
case 123:
YY_RULE_SETUP
#line 229 "picl.l"
{ yylval.st = copythru(yytext); BEGIN A; return(DEFNAME); }
	YY_BREAK
case 124:
YY_RULE_SETUP
#line 230 "picl.l"
return(UNTIL);
	YY_BREAK
case 125:
YY_RULE_SETUP
#line 232 "picl.l"
{ ifsw = 1; return(IF); }
	YY_BREAK
case 126:
YY_RULE_SETUP
#line 233 "picl.l"
{ if (!ifsw) { yylval.i = THEN; return(ATTR); }
		  yylval.p = delimstr("then part"); ifsw = 0;
		  return(THENSTR); }
	YY_BREAK
case 127:
YY_RULE_SETUP
#line 236 "picl.l"
{ yylval.p = delimstr("else part"); return(ELSESTR); }
	YY_BREAK
case 128:
YY_RULE_SETUP
#line 238 "picl.l"
{ BEGIN sh;
		  if ((delim = input()) == '{') delim = '}';	/* no nested {} */
		  shell_init(); }
	YY_BREAK
case 129:
YY_RULE_SETUP
#line 241 "picl.l"
{ struct symtab *p;
		  if (yytext[0] == delim) {
			shell_exec();
			BEGIN A;
		  } else {
			p = lookup(yytext);
			if (p != NULL && p->s_type == DEFNAME) {
				c = input();
				xxunput(c);
				if (c == '(')
					dodef(p);
				else
					pbstr(p->s_val.p);
			} else
				shell_text(yytext);
		  }
		}
	YY_BREAK
case 130:
/* rule 130 can match eol */
YY_RULE_SETUP
#line 258 "picl.l"
{ if (yytext[0] == delim) {
			shell_exec();
			BEGIN A;
		  } else
			shell_text(yytext);
		}
	YY_BREAK
case 131:
YY_RULE_SETUP
#line 265 "picl.l"
{ BEGIN def; }
	YY_BREAK
case 132:
YY_RULE_SETUP
#line 266 "picl.l"
{ definition(yytext); BEGIN A; }
	YY_BREAK
case 133:
YY_RULE_SETUP
#line 267 "picl.l"
{ undefine(yytext); }
	YY_BREAK
case 134:
YY_RULE_SETUP
#line 269 "picl.l"
{ yylval.i = 1; return(NTH); }
	YY_BREAK
case 135:
YY_RULE_SETUP
#line 270 "picl.l"
{ yylval.i = atoi(yytext); return(NTH); }
	YY_BREAK
case 136:
YY_RULE_SETUP
#line 271 "picl.l"
{
		  	yylval.f = atof(yytext); return(NUMBER); }
	YY_BREAK
case 137:
YY_RULE_SETUP
#line 274 "picl.l"
{	struct symtab *p;
		p = lookup(yytext);
		if (p != NULL && p->s_type == DEFNAME) {
			c = input();
			xxunput(c);
			if (c == '(')	/* it's name(...) */
				dodef(p);
			else {	/* no argument list */
				pbstr(p->s_val.p);
				dprintf("pushing back `%s'\n", p->s_val.p);
			}
		} else if (islower(yytext[0])) {
			yylval.p = tostring(yytext);
			return(VARNAME);
		} else {
			yylval.p = tostring(yytext);
			return(PLACENAME);
		}
	}
	YY_BREAK
case 138:
YY_RULE_SETUP
#line 294 "picl.l"
{ BEGIN str; clen=0; }
	YY_BREAK
case 139:
YY_RULE_SETUP
#line 295 "picl.l"
{ cbuf[clen]=0; yylval.p = tostring(cbuf); BEGIN A; return(TEXT); }
	YY_BREAK
case 140:
/* rule 140 can match eol */
YY_RULE_SETUP
#line 296 "picl.l"
{ cbuf[clen]=0; WARNING("missing quote in string \"%s\"", cbuf);
				BEGIN A; return(ST); }
	YY_BREAK
case 141:
YY_RULE_SETUP
#line 298 "picl.l"
{ cbuf[clen++]='"'; }
	YY_BREAK
case 142:
YY_RULE_SETUP
#line 299 "picl.l"
{ cbuf[clen++]='\t'; }
	YY_BREAK
case 143:
YY_RULE_SETUP
#line 300 "picl.l"
{ cbuf[clen++]='\\'; }
	YY_BREAK
case 144:
YY_RULE_SETUP
#line 301 "picl.l"
{ CADD; }
	YY_BREAK
case 145:
YY_RULE_SETUP
#line 303 "picl.l"
;
	YY_BREAK
case 146:
YY_RULE_SETUP
#line 305 "picl.l"
return(yylval.i = yytext[0]);
	YY_BREAK
case 147:
YY_RULE_SETUP
#line 307 "picl.l"
ECHO;
	YY_BREAK
#line 2019 "<stdout>"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(A):
case YY_STATE_EOF(str):
case YY_STATE_EOF(def):
case YY_STATE_EOF(xsc):
case YY_STATE_EOF(br):
case YY_STATE_EOF(thru):
case YY_STATE_EOF(sh):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 609 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 609 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 608);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = (c == '\n');

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 307 "picl.l"


#ifdef	FLEX_SCANNER
void xxcruft(void)
{
	unput(0);
}
#endif	/* FLEX_SCANNER */

